import Image from 'next/image';
import Link from 'next/link';
import { Info, Star } from 'lucide-react';
import Carousel from '@/components/Carousel';
import HeroVideo from '@/components/HeroVideo';
import { Actions } from '@/components/ClientActions';
import { homeData, image, mediaType, title, year } from '@/lib/tmdb';
export default async function Home() { try {
    const [trend, popular, top, upcoming, tv] = await homeData();
    const hero = trend.results.find(x => x.backdrop_path && x.media_type !== 'person') || trend.results[0];
    const isSpiderMan = title(hero).toLowerCase().includes('spider-man');
    return <main><section className="relative flex min-h-[760px] items-end overflow-hidden px-5 pb-20 pt-28 md:px-16"><Image preload fill src={image(hero.backdrop_path, 'original')} alt="" className="ken-burns object-cover"/>{isSpiderMan && <HeroVideo />}<div className="hero-mask absolute inset-0"/><div className="relative z-10 mx-auto w-full max-w-screen"><div className="max-w-3xl"><div className="anim-fade-up mb-4 flex items-center gap-3 text-sm text-muted"><span className="flex items-center gap-1 rounded bg-gold px-2 py-1 font-bold text-black"><Star className="h-4 w-4 fill-current"/>{hero.vote_average?.toFixed(1)}</span><span>{year(hero)}</span><span>•</span><span>{mediaType(hero) === 'movie' ? 'Movie' : 'TV Series'}</span></div><h1 className="anim-fade-up delay-1 text-5xl font-extrabold tracking-tight md:text-7xl">{title(hero)}</h1><p className="anim-fade-up delay-2 my-6 line-clamp-2 max-w-2xl text-base leading-7 text-gray-300 md:text-lg">{hero.overview}</p><div className="anim-fade-up delay-3 flex flex-wrap gap-3"><Actions item={hero}/><Link href={`/${mediaType(hero)}/${hero.id}`} className="flex items-center gap-2 rounded-full bg-white/10 px-5 py-3 font-semibold backdrop-blur hover:bg-white/20 active:scale-95"><Info />More Info</Link></div></div></div></section><div className="mx-auto flex max-w-screen flex-col gap-20 px-5 py-10 md:px-16"><Carousel title="Trending Now" items={trend.results.filter(x => x.media_type !== 'person')}/><Carousel title="Top 10 This Week" items={trend.results.filter(x => x.media_type !== 'person').slice(0, 10)} ranked/><Carousel title="Popular Movies" items={popular.results}/><Carousel title="Top Rated" items={top.results}/><Carousel title="Coming Soon" items={upcoming.results}/><Carousel title="Popular TV Shows" items={tv.results.map(x => ({ ...x, media_type: 'tv' }))}/></div></main>;
}
catch (e) {
    return <SetupError error={e instanceof Error ? e.message : 'Unknown TMDB error'}/>;
} }
function SetupError({ error }) { const missing = error.includes('not configured'); return <main className="grid min-h-[75vh] place-items-center px-6 pt-24"><div className="max-w-xl rounded-2xl border border-gold/20 bg-surface p-10 text-center"><div className="mx-auto mb-6 w-fit rounded bg-gold px-3 py-2 text-3xl font-black text-black">IMDb</div><h1 className="text-3xl font-bold">{missing ? 'Connect TMDB to start exploring' : 'Unable to reach TMDB'}</h1><p className="mt-4 leading-7 text-muted">{missing ? <>Add your TMDB credential to <code className="text-gold">TMDB_API_KEY</code>, then restart the server.</> : <>Your API key is configured, but the TMDB request failed. Check your internet, VPN, DNS or firewall and restart the server.</>}</p><p className="mt-4 rounded bg-black/30 p-3 text-xs text-muted">{error}</p></div></main>; }
